spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cms_movie
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect

redis:
  standalone:
    host: 127.0.0.1
    port: 6379
    database: 0
